version: "2"


services:
  web:
    container_name: web
    build: web
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:80"

  # app
  app:
    image: tutum/hello-world
    restart: unless-stopped
    networks:
      backend:
        aliases:
          - apps
    expose:
      - 80
    depends_on:
      - web

networks:
  backend:
      driver: bridge
